### ISSUE TITLE
validate方法只有eq 吗？  能否支持下contains或者其他类型的验证？

### ISSUE THREAD

**Issue by HD-charleschen** [HttpRunner/har2case#12]
validate方法只有eq 吗？  能否支持下contains或者其他类型的验证？

**Comment by debugtalk** [comment]
@HD-charleschen 生成的用例只有 eq，其它校验方式可以自己写。

http://httprunner.org/write-testcases/#Comparator

**Comment by HD-charleschen** [comment]
作者你好：

由于目前本人的py编码能力较弱， 添加验证方式的时候遇到困难，你的博客里面说改这三个类：然后我看了源码， context.py , validator.py里面都有do_validation  和validate  类，而parse_validator在  testcase类 
所以不清楚怎么加上你这边本身就支持的  comparator表里面的其他验证方法。。。

能否抽空截图示意下？ 
非常感谢

**Comment by HD-charleschen** [comment]
应该不用改了，我已经明白了，不好意思，请无视上面的问题。
