### ISSUE TITLE
har转case时的问题。具体看描述

### ISSUE THREAD

**Issue by RongshanZhang** [HttpRunner/har2case#13]
![image](https://user-images.githubusercontent.com/19358469/46728852-565f4b00-ccb6-11e8-94e7-0d2f806ce553.png)

您好，请问一下，遇到这种情况下怎么解决呢？我是chrome中导出的har文件。
因为之前导出的har都是小文件，都可以转化为用例，但是这次文件很大很杂，尝试了只是把其中的一部分提取出来，但是还是不行，所以请问一下到底是什么问题呢？谢谢！

**Comment by debugtalk** [comment]
麻烦提供下你的 har 文件。

**Comment by RongshanZhang** [comment]
[loginend.har.zip](https://github.com/HttpRunner/har2case/files/2464196/loginend.har.zip)

**Comment by debugtalk** [comment]
@RongshanZhang 修复了，使用 master 分支升级下。
