### ISSUE TITLE
现在生成 validate 的时候，只解析支持 dict 类型的 json 吗

### ISSUE THREAD

**Issue by asdf2014** [HttpRunner/har2case#17]
如果是 `[{a:a},{b:b},...]` 这样的，dict 外层嵌套数组的情况，不支持吗

```python
if not isinstance(resp_content_json, dict):
    return
```

**Comment by asdf2014** [comment]
@debugtalk 在的吗，我这边可以完善这个特性，但是想知道您是怎么看这个问题的

**Comment by asdf2014** [comment]
@debugtalk 尝试写了一个实现，我这边测试了一把，没什么问题。方便的时候帮忙看看吧 #18

**Comment by debugtalk** [comment]
@asdf2014 感谢反馈，之前我的确是没有遇到过 body 部分为 list 的情况。这部分可以兼容处理下。
