### ISSUE TITLE
exclude支持同时指定多个条件

### ISSUE THREAD

**Issue by aspstar** [HttpRunner/har2case#5]
har2case的过滤是如何实现的？--exclude只能对一个词进行过滤，例如想对css和js等多个词进行过滤就没办法实现。har2case pm.har pm.yml --exclude css，js啥都过滤不了，har2case pm.har pm.yml --exclude css --exclude js只能过滤js，请问作者如果想同时过滤JS和CSS如何实现？

**Comment by debugtalk** [comment]
@aspstar 是的，当前只支持单一条件的过滤，要实现多个条件过滤也方便，我优化下。
