### ISSUE TITLE
python2的转换的yaml文件结果不太友好啊

### ISSUE THREAD

**Issue by vonhehe** [HttpRunner/har2case#7]
python2装换结果如下图：
![python2转换结果图](https://user-images.githubusercontent.com/27840855/36767222-8418a552-1c74-11e8-9758-aebfa97f81da.png)

python3装换结果如下图：
![python3转换结果图](https://user-images.githubusercontent.com/27840855/36767189-66eddca4-1c74-11e8-8cc5-4a111b0b4779.png)

唉，编码问题啊，头疼

**Comment by debugtalk** [comment]
这个问题无解，推荐使用 Python3。
